import localFont from "next/font/local";
import "./globals.scss";
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false;
const avenirBook = localFont({
  src: "./fonts/Avenir-Book.woff",
  variable: "--font-avenir-book", 
  weight: "100 900",
});
const avenirBlack = localFont({
  src: "./fonts/Avenir-Black.woff",
  variable: "--font-avenir-black", 
  weight: "100 900",
});

export const metadata = {
  title: "Mohan Arjunan",
  description: "Generated by create next app",
};

// Aos .init()

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${avenirBook.variable} ${avenirBlack.variable}`}>
        {children}
      </body>
    </html>
  );
}
